### ISSUE TITLE
UI : Optionally give user the selection to Update Patient External alongwith Change Patient ID External

### ISSUE THREAD

**Issue by vrindanayak** [dcm4che/dcm4chee-arc-light#1031]
- Invoke [Update Patient External](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger.json#/HL7-RS/UpdatePatientExternal) and [Change Patient ID External](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger.json#/HL7-RS/ChangePatientIDExternal) services if : 
  - `Update Patient checkbox is selected` and 
  -  `User changes either of PatientID/IssuerOfPatientID/IssuerOfPatientIDQualifiersSequence and any other patient attributes`

- Related #1030

**Comment by shral** [comment]
For now I'm checking, if the user changes only the IDs (PatientID / IssuerOfPatientID / IssuerOfPatientIDQualifiersSequence) than I'm calling the "Change Patient ID External" if the user changes some of the attributes but not the patient id than I'm calling the service "Update Patient External", and if the user changes both than I'm calling both services, so I don't see the reason why I should add another checkbox ("Update Patient checkbox) that's why I'm closing this issue unless I misunderstood the issue.
