### ISSUE TITLE
 Caused by: java.lang.UnsatisfiedLinkError: D:\\wildfly-11.0.0.Final\\modules\\org\\dcm4che\\imageio\\main\\lib\\win-x86_64\\opencv_java.dll: %1 不是有效的 Win32 应用程序。"}}

### ISSUE THREAD

**Issue by yuewei1987** [dcm4che/dcm4chee-arc-light#1296]
Caused by: java.lang.UnsatisfiedLinkError: D:\\wildfly-11.0.0.Final\\modules\\org\\dcm4che\\imageio\\main\\lib\\win-x86_64\\opencv_java.dll: %1 not Win32 "}}

**Comment by yuewei1987** [comment]
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b25)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)

**Comment by gunterze** [comment]
You would have to use the HEAD version of (not yet released) dcm4che-jboss-modules-5.13.0

**Comment by yuewei1987** [comment]
yes I use  the  dcm4che-jboss-modules-5.13.0

**Comment by gunterze** [comment]
win-x86_64/opencv_java.dll is a 64-bit DLL, but it requires other DLLs and perhaps, you have a 32-bit instead of a 64-bit version of one of that DLLs on your system.

**Comment by nroduit** [comment]
I haven't tried with the archive but with the toolkit doesn't handle correctly the VM architecture. Here is a proposal of [fix](https://github.com/dcm4che/dcm4che/pull/260).

However, I'm not sure it will fix this issue. There is something weird in the message because it is like you are running in the 32-bit VM and asking for the 32-bit native library. Using JAVA_HOME on Windows is sometimes problematic => mixing the architecture with the default java command from the registry.

The library is compiled with minimal dependencies. On windows only with core system libraries.
![lib-32](https://user-images.githubusercontent.com/993975/37818065-31be0c72-2e79-11e8-9fd7-410f4d788307.png)

**Comment by gunterze** [comment]
In wildfly, the module loader should take care to put the right directory into the library path: s. https://jboss-modules.github.io/jboss-modules/manual/#native-libraries
