### ISSUE TITLE
UI dicom object upload fails with docker image

### ISSUE THREAD

**Issue by bonapat** [dcm4che/dcm4chee-arc-light#1457]
I deployed the docker compose config (minimum set) as described in doc 'Running on Docker'.
It run basically pretty well, except the UI Upload function "Upload DICOM Object" doesn't work at all.
If I try to upload a dicom object  a message shows up: Error 0.

The same object can be uploaded by network c-store without any issues.

**Comment by shral** [comment]
@bonapat I cannot reproduce the bug, Is it possible to send us the file what are you trying to upload and the log file part where the upload request it's happening?

**Comment by bonapat** [comment]
The log files don't show anything. But attached is the file I tried.
I attached some print screen as well. On the older version 5.10.5 installed without docker it worked well.

Dialog after upload (Version 5.13.1 with docker on ubuntu) Failed:
![image](https://user-images.githubusercontent.com/33900690/41551050-ec50e9ba-732a-11e8-9fbb-5c12cbe399f1.png)

Dialog after upload (Version 5.10.5 without docker on ubuntu) Passed:
![image](https://user-images.githubusercontent.com/33900690/41551198-77883c68-732b-11e8-9ee8-2c7ab85584f9.png)

Testdata:
[Testdata.zip](https://github.com/dcm4che/dcm4chee-arc-light/files/2112245/Testdata.zip)

**Comment by shral** [comment]
I have tested uploading your test data, it's working fine on my side! To be sure that that's not a UI bug, Can you open the browser inspect (in chrome F12) go to Network tab and trigger the upload again, and post the URL what is used and the response of the upload query.

**Comment by gunterze** [comment]
Unable to reproduce with dockerized 5.13.2 ([docker-compose.yml](https://github.com/dcm4che-dockerfiles/dcm4chee-arc-psql/blob/5.13.2/docker-compose.yml)).

**Comment by nush-1qb** [comment]
I am able to reproduce this with [5.19.0](https://github.com/dcm4che-dockerfiles/dcm4chee-arc-psql/blob/5.19.0/docker-compose.yml) when I am deploying on GKE.

Lets say I have `pacs.test.com` pointing to port 8080 of the archive.

When I access the archive through pacs.test.com, and then click "upload DICOM", I will get an Error0 on the UI, and the REST call that fails shows: http://127.0.0.1:8080/dcm4chee-arc/aets/DCM4CHEE/rs/studies instead of http://pacs.test.com/dcm4chee-arc/aets/DCM4CHEE/rs/studies

So I am guessing there is a way to configure the `dicomHostname` for STOW-RS?

**Comment by nush-1qb** [comment]
Found it: https://github.com/dcm4che-dockerfiles/slapd-dcm4chee#archive_host

**Comment by nush-1qb** [comment]
Ok, so my original hypothesis was that the error was due to a mismatch of the request-url and request origin.

Before I configured the `ARCHIVE_HOST` env variable on the `ldap` deployment, the rest call was going to http://127.0.0.1:8080/dcm4chee-arc/aets/DCM4CHEE/rs/studies

Then I tried port forwarding to port 8080 so that I can access my remote service (pointed to by pacs.test.com) locally via localhost:8080. When i did that, the host of the origin url (localhost:8080) matched that of the request url (127.0.0.1:8080), and so the rest call was successful, and the file successfully uploaded. 

Then I thought, ok let's set the `ARCHIVE_HOST` to the service name of my archive deployment (`pacs-arc`). 

Here is what I observed:

When I tried uploading on pacs.test.com, the REST call went to http://pacs.test.com/dcm4chee-arc/aets/DCM4CHEE/rs/studies, which I expected to work, and yet it failed again.

When I tried uploading via port-forwarding localhost:8080, the REST call went to http://pacs-arc:8080/dcm4chee-arc/aets/DCM4CHEE/rs/studies and failed, I was assuming because the origin-url (localhost:8080) did not match with request-url (pacs-arc:8080), but I don't know for sure anymore.

Can we please re-open this issue? @gunterze @shral

**Comment by gunterze** [comment]
Tested upload of DICOM and JPEG + JSON Metadata via the UI successfully with 5.19.0!

**Comment by nush-1qb** [comment]
@gunterze Thanks I can get it to work locally as well, the issue happens when I deploy to my cloud provider.

Tinkered around a little more, and now I am able to get this error in my console:

```
main.42d835b146076810b8a0.bundle.js:1 Mixed Content: The page at 'https://pacs.test.com/dcm4chee-arc/ui2/#/studies' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://pacs-arc:8080/dcm4chee-arc/aets/DCM4CHEE/rs/studies'. This request has been blocked; the content must be served over HTTPS.
```

So how can I make that call use HTTPS instead? Do I need to follow [this article](https://dcm4che.atlassian.net/wiki/spaces/ee2/pages/2556078/Setting+up+DCM4CHEE+with+TLS+encryption), or is there a better guide?

**Comment by gunterze** [comment]
Configure a https connection, and select it in the DCM4CHEE Web Application.
![Screenshot from 2019-10-15 15-06-43](https://user-images.githubusercontent.com/400095/66834399-ceadbb80-ef5d-11e9-843c-84f48b91e4a0.png)
![Screenshot from 2019-10-15 15-07-44](https://user-images.githubusercontent.com/400095/66834400-ceadbb80-ef5d-11e9-95b2-beee86eb428f.png)
![Screenshot from 2019-10-15 15-08-44](https://user-images.githubusercontent.com/400095/66834401-ceadbb80-ef5d-11e9-8719-f28066128be9.png)

**Comment by gunterze** [comment]
Best would be if you could provide a wiki page about running the services on Kubernetes, beside [Distribute secured archive services and Elastic Stack over several hosts using Docker Swarm](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Distribute-secured-archive-services-and-Elastic-Stack-over-several-hosts-using-Docker-Swarm)
