### ISSUE TITLE
Support for WADO-RS Retrieve Rendered Transaction

### ISSUE THREAD

**Issue by hackermd** [dcm4che/dcm4chee-arc-light#1617]
Method | Path | Name
-- | -- | --
GET | /dcm4chee-arc​/aets​/{aet}​/rs​/studies​/{study}​/rendered | [Retrieve Rendered Study](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/WADO-RS/RetrieveRenderedStudy)
GET | ​/dcm4chee-arc​/aets​/{aet}​/rs​/studies​/{study}​/series​/{series}​/rendered | [Retrieve Rendered Series](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/WADO-RS/RetrieveRenderedSeries)
GET | /dcm4chee-arc​/aets​/{aet}​/rs​/studies​/{study}​/series​/{series}​/instances​/{instance}​/rendered | [Retrieve Rendered Instance](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/WADO-RS/RetrieveRenderedInstance)
GET | /dcm4chee-arc​​/aets​/{aet}​/rs​/studies​/{study}​/series​/{series}​/instances​/{instance}​/frames​/{frames}​/rendered | [Retrieve Rendered Frames](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/WADO-RS/RetrieveRenderedFrames)

Limitations:
- [Image Annotation Query Parameter](http://dicom.nema.org/medical/dicom/current/output/html/part18.html#sect_8.3.5.1.1) `annotation` is not considered.
- [Character Set Query Parameter](dicom.nema.org/medical/dicom/current/output/html/part18.html#sect_8.3.3.2) `charset` is  not considered.
- Always `linear` VOI windowing is applied, independent of the given function name by [Windowing Query Parameter](http://dicom.nema.org/medical/dicom/current/output/html/part18.html#sect_8.3.5.1.4) `window`.
- [ICC Profile Query Parameter](dicom.nema.org/medical/dicom/current/output/html/part18.html#sect_8.3.5.1.5) `iccprofile` is  not considered.
- Only rendering of Grayscale Softcopy Presentation State Storage SOP Instances is supported, and only the grayscale pipeline and overlays will be applied to referenced images.

**Comment by hackermd** [comment]
That's great news. Please let me know if I can help with testing.

**Comment by hackermd** [comment]
@gunterze thank you for implementing support for retrieve rendered transaction. I am afraid, however, that frame-level retrieval is not implemented correctly.

```none
curl -I http://localhost:8080/dcm4chee-arc/aets/DCM4CHEE/rs/studies/{StudyInstanceUID}/series/{SeriesInstanceUID}/instances/{SOPInstanceUID}/frames/{FrameNumber}/rendered
HTTP/1.1 200 OK
Server: nginx/1.17.0
Date: Sat, 21 Sep 2019 22:50:25 GMT
Content-Type: multipart/related;start="<dcde0915-7300-413b-8c86-bda362d95e7b@resteasy-multipart>";type="image/jpeg"; boundary=51da5266-6a2c-4e30-975b-919f07dad3a6
```

The response message is not supposed to contain a multipart-related payload.

In addition, the service doesn't accept rendered media types (e.g., `image/jpeg`):

```none
curl -I -H 'Accept: image/jpeg' http://localhost:8080/dcm4chee-arc/aets/DCM4CHEE/rs/studies/{StudyInstanceUID}/series/{SeriesInstanceUID}/instances/{SOPInstanceUID}/frames/{FrameNumber}/rendered
HTTP/1.1 406 Not Acceptable
Server: nginx/1.17.0
Date: Sat, 21 Sep 2019 22:53:12 GMT
```

Please see [DICOM PS3.18 Section 8.7.4](http://dicom.nema.org/medical/dicom/current/output/html/part18.html#sect_8.7.4).

**Comment by gunterze** [comment]
It's intended. I still follow PS 3.18 2019a, which declares that all WADO-RS services have to return multipart/related content type - with the exception of the retrieve of metadata, which also supports application/json+dicom - independently if the response only contains one or multiple objects. There were lot of inconsistencies introduced and information lost by the rewrite of PS 3.18 in 2019b - I will write a CP when I find time. Only for retrieve of thumbnails I followed 2019c - because there is always just one thumbnail returned. So  if you want to get one frame rendered not wrapped in a multipart mime type, you may use the thumbnail service for a single frame.

**Comment by hackermd** [comment]
I think this is incorrect and incompliant with the standard. Based on my understanding, also the 2019a edition of the standard required WADO-RS Retrieve Rendered Transaction to respond with a single-part message (see [PS3.18 6.1.1.3 2019a](http://dicom.nema.org/medical/dicom/2019a/output/chtml/part18/chapter_6.html#sect_6.1.1.3) and [PS3.18 6.1.1.4 2019a](http://dicom.nema.org/medical/dicom/2019a/output/chtml/part18/chapter_6.html#sect_6.1.1.4)).

**Comment by gunterze** [comment]
WADO-RS Retrieve Rendered Transaction  was inconsistent with the existing other WADO-RS Services from its beginning. WADO-RS Retrieve Rendered Transaction must use multipart, because it may return multiple objects. Making the content-type dependent on the number of matches is poor design.

**Comment by hackermd** [comment]
> WADO-RS Retrieve Rendered Transaction was inconsistent with the existing other WADO-RS Services from its beginning. WADO-RS Retrieve Rendered Transaction must use multipart, because it may return multiple objects. Making the content-type dependent on the number of matches is poor design.

My understanding is that the whole idea of the Retrieve Rendered Transaction service is to always render into and return a single object to facilitate display by non-DICOM software such as browsers. For example, multiple frames could be rendered into `image/gif` or `video/mpeg`.

I asked a related question in December 2018 in WG27 and @dclunie confirmed that Retrieve Rendered Transaction does not use multipart-related. 

It would be great if dcm4chee-arc-light would implement this service in a standard compliant manner.

**Comment by gunterze** [comment]
That only would make sense for Target Resource Frame and Instance, and later only if it's not a Presentation State - will discuss the issue with  @dclunie

**Comment by dclunie** [comment]
Short version:

You need to be able to return a single part image/jpeg (if the response is a single rendered media type image).

Long version ...

In December 2018 in WG27 I wrote (with the links updated to 2019a, the last pre-redoc of PS3.18 release), and nobody contradicted me (for what that's worth):

_'PS3.18 states very clearly that the request and response are a
"rendered media type":

  http://dicom.nema.org/medical/dicom/2019a/output/chtml/part18/sect_6.5.8.html#sect_6.5.8.1

  http://dicom.nema.org/medical/dicom/2019a/output/chtml/part18/sect_6.5.8.3.html

with absolutely no mention of multipart.

I.e., it should be:

  Accept: 1#rendered-media-type CRLF

just like it says.

The only parameters permitted AFAIK are those for the weighting
of different media types if more than one.

Indeed I know quite a few folks who use RetrieveRendered for images
that have a native image/jpeg payload encoded in DICOM, just so that
they can avoid dealing with the multi-part stuff (e.g., this is a
common pattern in the WG 26 WSI Connectathons), even though there is
no real "rendering" going on the payload is copied as is).

This begs the question of what to do if there is more than one instance
in the response, but the request/response text is very clear.'_

So that was my opinion back then and it hasn't changed.

Since the PS3.18 re-doc, it is still documented as returning a rendered media type:

http://dicom.nema.org/medical/dicom/current/output/chtml/part18/sect_10.4.html#para_740d0b3f-255c-4916-bdc8-73dd445aa37c

"Rendered Resources" "The content type of the response payload shall be a Rendered Media Type. See Section 8.7.4."

Note also:

http://dicom.nema.org/medical/dicom/current/output/chtml/part18/sect_10.4.3.3.html

"The payload may be single part or multipart depending on the media type"

So the question of what to do when there are multiple frames in the response remains unclear.

I won't editorialize on the quality of the design at this time.

AFAIK, the viewers used in the WG 26 Connectathon are dependent on receiving a single image/jpeg file in the retrieve rendered response, and that is what they are asking for in the Accept header.

David

PS. This also begs the question of whether or not multipart specified in the Accept header is relevant to what is returned. I.e., the requestor may specify whether or not a single response part is expected, as opposed to it depending on how many parts the server comes up with based on the resource.

I.e.:

Accept: image/jpeg

versus

Accept: multipart/related; type=image/jpeg

I also note your interesting discussion at:

https://stackoverflow.com/questions/36332842/how-to-specify-to-accept-multipart-related-content-type-with-particular-content

**Comment by gunterze** [comment]
I never liked how DICOM specified WADO-RS Rendered Retrieve Transaction, but because I did not found time to start implementing it until recently, the pain was not enough to formulate my veto before it becomes final ;) .

I am in doubt, if who wrote

> "The payload may be single part or multipart depending on the media type"

really meant, that the selected media-type should depend on the number of calculated matches for the retrieve request.

> [8.7.8.1 Selected Media Type](http://dicom.nema.org/medical/dicom/current/output/html/part18.html#sect_8.7.8.1)
> ...
> The Selected Media Type of each message part depends on the Resource Category of the Instance and the Acceptable Media Types for that Resource Category.

only refer the "Resource Category", not the number of objects to return.

But I am not too interested about the interpretation of the current wording of the standard text - there are better tools for specifying RESTful APIs unambiguous than prose...

I rather argue with the advantage of WADO-RS over WADO-URI, and that is for us (J4Care) the possibility to be able to request all objects (dicom/rendered/bulkdata) of one entity (study/series) by one request, without the need to fetch individual instance uids upfront.

I actually see no advantage of WADO-RS over WADO-URI for just getting one (dicom or rendered) object.

Anyway, I will extend the WADO-RS Retrieve Rendered Transaction for Instances and Frames implementation to  - dependent on the Accept Header - also to behave like WADO-URI, and return the rendered object with single part mediatype.

**Comment by hackermd** [comment]
> selected media-type should depend on the number of calculated matches for the retrieve request

My interpretation of the standard is that, per definition, the Retrieve Rendered Transaction RESTful service renders all matching DICOM objects into a single resource part and hence always only returns a single part, i.e., there should never be a situation where the service would have to return multiple parts.

To me, the main question is rather how an origin server would determine how to render a set of DICOM objects into an acceptable rendered media type. The behavior of the origin server doesn't seem to be explicitly defined anywhere in the standard - only a few examples are given.

As @gunterze pointed out, rendering behavior is intuitive for a single-frame image instance, an individual frame of a multi-frame image instance, or a SR document instance. It gets trickier for a series of single-frame image instances or multiple frames of a multi-frame image instance. For example, should the origin server sort instances somehow before rendering multiple pixel planes into a gif or a video? How rendering is supposed to work at the study-level is a complete mystery to me..
