### ISSUE TITLE
UI: Open Viewer: Provide the possibility to send the access token to the url as parameter

### ISSUE THREAD

**Issue by shral** [dcm4che/dcm4chee-arc-light#1738]
`...requestType=STUDY&studyUID={}&access_token={}&target=_self`
`...requestType=PATIENT&patientID={}&access_token={}&target=_blank`

**Comment by nroduit** [comment]
Yes, this is a standard way.

A more secure implementation would be to pass it into the http header (with https the token cannot be intercepted).
`Authorization: Bearer $token
`
Concerning the time, 5 min could be not enough is some situations when the exam to download is big and the connexion is over the Internet (as the wado URI service is requested sequentially by image). 

Another small issue: would be possible to have a parameter to not open the URL in a new window because in our case the viewer will be open at system level. This will avoid to always open an empty page.

**Comment by nroduit** [comment]
It sounds good.

I've implemented the transmission of the token to the WADO request, see https://github.com/nroduit/weasis-pacs-connector/issues/23https://github.com/nroduit/weasis-pacs-connector/issues/23
