### ISSUE TITLE
DCM4CHEE 5.19 enormous metadata result

### ISSUE THREAD

**Issue by spalte** [dcm4che/dcm4chee-arc-light#2217]
**Describe the bug**
With DCM4CHEE 5.19, when doing a study level multipart request (ie. /studies/{studyuid}/metadata) the resulting json is enormous with extra Original Attributes Sequence Attribute (0400,0561) containing  repeatedly coerced attributes for Series Time (0008,0031). At https://download.naturalimage.ch/multipart.json (~200MB) you can download an example of a result from /metadata.

**Comment by gunterze** [comment]
Seems the received objects of one Series differs in its value for Series Time (0008,0031) which has to be coerced  by the archive, which is recorded in the Original Attributes Sequence Attribute (0400,0561). You may change the default value of the Attribute Update Policy of the Series Attribute Filter from OVERWRITE to SUPPLEMENT, so the value will be coerced in the received object, instead of coercing the value in all previous received instances, which will reduce the number of recorded attribute coercions.
The issue should be reported to the vendor of the modality which created that objects, because using different values for Series attributes of objects with equal Series Instance UID is definitely incorrect.

**Comment by spalte** [comment]
The series in question is the old ANEURIX dataset that was publicly available for many years on the OsiriX website. You can download it from https://download.naturalimage.ch/ANEURIX.zip
 It appears to me that the Series Time for every instance is 133341.000000. The Acquisition Time varies between the instances though, which I understand to be permissible. It appears to me that dcm4chee is getting confused between the Series Time and the Acquisition Time, or something like that, and doing some weird coercing.

**Comment by gunterze** [comment]
I could not reproduce the issue. After sending https://download.naturalimage.ch/ANEURIX.zip to dcm4chee-arc, the returned JSON metadata for that study only had 2323k
```
$ curl -O http://localhost:8080/dcm4chee-arc/aets/DCM4CHEE/rs/studies/2.16.840.1.113669.632.20.1211.10000744858/metadata
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2323k    0 2323k    0     0  8574k      0 --:--:-- --:--:-- --:--:-- 8574k
```
and does not include any Original Attributes Sequence Attribute (0400,0561)!

**Comment by spalte** [comment]
I have been trying to reproduce this again today, and have just not been able to. I will keep on looking to see if I can come up with an explanation with regard to what happened, and I will get back to you if I have any more info. Thank you so much for your time and for having looked into it, and I apologize for having wasted your time.
