### ISSUE TITLE
White Pixels when compress imagens (any tranfersyntax)

### ISSUE THREAD

**Issue by thiagobusa** [dcm4che/dcm4chee-arc-light#2281]
**Describe the bug**
When dcm4chee-arc compress imagens (any  compress tranfersyntax) the white pixels appears

**To Reproduce**
1. Configure dcm4chee-arc to compress imagens on receive
2. Send studies (attached)

**Expected behavior**
Compress imagens correctly

**Screenshots**
Before compress
![2](https://user-images.githubusercontent.com/5495168/69752228-88887200-112f-11ea-81f7-fd55b97974a6.png)

After compress
![1](https://user-images.githubusercontent.com/5495168/69752225-858d8180-112f-11ea-9f68-3a0d7c56213d.png)

**Additional context**
Using dcmtk (dcmcjpeg) works fine
[Axial T1 FSE-compress-1.2.840.10008.1.2.4.70.zip](https://github.com/dcm4che/dcm4chee-arc-light/files/3898442/Axial.T1.FSE-compress-1.2.840.10008.1.2.4.70.zip)
[Axial T1 FSE-uncompress.zip](https://github.com/dcm4che/dcm4chee-arc-light/files/3898443/Axial.T1.FSE-uncompress.zip)

**Comment by gunterze** [comment]
Not reproducible with dcm4chee-arc 5.19.1 with [Image Writer](https://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/config/imageWriter.html) attributes:

Name | Value
-- | --
Transfer Syntax | 1.2.840.10008.1.2.4.70
Image IO Writer Format Name | jpeg-cv
Java Class Name | org.dcm4che3.opencv.NativeJPEGImageWriter
Image Write Param | compressionType=LOSSLESS-1

(= default configuration)

**Comment by gunterze** [comment]
Guess the problem is caused by your viewer, which does not concern signed Pixel Data correctly:

The original pixel data contains bytes which bits 13-16 set to 1, which get lost by compressing with 12 bit precision - particular ffffH becomes 0fffH - and your viewer seems to use bit 16 as sign-bit, ignoring the value of BitsStored = 12.

**Comment by nroduit** [comment]
I didn't look in detail but the problem seems to come from the fact that the original image has signed pixels (-2047 to 2048), then converted to jpeg with unsigned pixels (0 to 4095).

I guess this special case is not handled correctly after the compression. According to [DICOM](http://dicom.nema.org/medical/dicom/current/output/chtml/part05/sect_8.2.html), jpeg should not used signed values.

The viewer extends the signed 12-bit LUT because the real pixel are outside this range.

**Comment by nroduit** [comment]
Sorry, with jpeg lossless having signed pixels is possible. So the jpeg compression should not return values between 0 and 4095.

**Comment by gunterze** [comment]
As far I have seen, only bits 13-16 are set to zero by compression with precision 12 after decompression, which should not effect the interpretation of 12 bit values as signed or unsigned by viewers taking care of  Bits Stored = 12.

**Comment by gunterze** [comment]
With dcm4che/dcm4che#599 you may configure

Name | Value
-- | --
Transfer Syntax | 1.2.840.10008.1.2.4.70
Image IO Writer Format Name | jpeg-cv
Java Class Name | org.dcm4che3.opencv.NativeJPEGImageWriter
Image Write Param | compressionType=LOSSLESS-1
Image Write Param | bitsCompressed=16
