### ISSUE TITLE
UI Navigation MWL tab: Only show Web Applications marked to support Service class MWL_RS in Drop-down list 

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#2472]
Related #2470

**Comment by vrindanayak** [comment]
`Submit` button is still available even if the dropdown is empty. This causes misleading error message to be seen `No Web Application selected`. 

Also due to #2469 if a query is performed on `Studies` tab first and then switched to MWL tab, from cache this Web Application is selected and user can perform MWL queries even with empty Web Application dropdown.

[2472_retest.pdf](https://github.com/dcm4che/dcm4chee-arc-light/files/4429650/2472_retest.pdf)

**Comment by shral** [comment]
Fixing https://github.com/dcm4che/dcm4chee-arc-light/issues/2469 should fix this too.
