### ISSUE TITLE
UI Navigation -> DIFFs tab : Compare Studies between archives services unavailable

### ISSUE THREAD

**Issue by vrindanayak** [dcm4che/dcm4chee-arc-light#2507]
[Compare Studies with/between external Archive(s)](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/DIFF-RS) services are not available in spite of configuring Web Application with `DCM4CHEE_ARC_AET_DIFF`, `QIDO_RS` and `QIDO_COUNT` as `Web Service Class`

[Test Steps](https://github.com/dcm4che/dcm4chee-arc-light/files/4403135/2507_UI_DIFFs-issue.pdf)

**Comment by shral** [comment]
In the diff Tab of the Navigation menu, you can trigger or show triggered diff results with one submit button as follows:
Trigger:
If you want to trigger a diff, you need to configure a WebApplication with the Web Service Class `DCM4CHEE_ARC_AET_DIFF`. (If you check the `Queued` checkbox it will only trigger the diff but not show the result because it will trigger an asynchronous diff otherwise you should see ther result of the diff if there is a diff).
Show:
- If you want to only show the (before triggered (asynchroneous by checking the `Queued` checkbox) diff you have to unselect (if selected) the WebApplication and add ether PK of the task (You can see the tasks triggered by the diff page in the Monitoring->diff page) or the Batch ID.

![image](https://user-images.githubusercontent.com/7990614/85299731-eef72800-b4a5-11ea-9c39-0fd0915e7580.png)
