### ISSUE TITLE
UI Navigation -> Studies : View DICOM Object on instance level missing for users configured with 'user' role

### ISSUE THREAD

**Issue by Milzor** [dcm4che/dcm4chee-arc-light#2747]
**Describe the bug**
User role doesn't get access to view dicom image in dcm4chee-arc-light UI. I followed the steps on https://github.com/dcm4che/dcm4chee-arc-light/wiki/User-Role-Access-to-Viewer, but once a regular user logs in it doesn't show the `View DICOM Object` in 

**To Reproduce**
1. Follow steps https://github.com/dcm4che/dcm4chee-arc-light/wiki/User-Role-Access-to-Viewer
2. Login as regular user.
3. Open any study.
4. Click the 3 dots.
5. Small popup doesn't show `View DICOM Object`

**Expected behavior**
The popup should show `View DICOM Object`

**Screenshots**
![image](https://user-images.githubusercontent.com/1233014/91552432-1649f580-e92c-11ea-8117-4112f446beac.png)
![image](https://user-images.githubusercontent.com/1233014/91552536-41344980-e92c-11ea-8455-7d89a2f434b0.png)

**Desktop (please complete the following information):**
 - All

**Additional context**
Logged in user has the role `user` and `user` role is added to the UI Configuration permissions. See screenshot.
Running docker images:
- dcm4che/dcm4chee-arc-psql:5.21.0-secure
- dcm4che/postgres-dcm4chee:12.2-22
- dcm4che/slapd-dcm4chee:2.4.48-22.0

**Comment by vrindanayak** [comment]
@Milzor : Issue is not related to the UI permission `Action - Studies - Open Viewer` - FYI, this UI permission relates to [Invoke Image Display](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Invoke-Image-Display) feature used in conjunction with [Weasis Viewer Integration](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Weasis-Viewer-Integration)

I've rectified the issue title to clearly indicate the bug. Thank you for reporting the issue!

**Comment by shral** [comment]
First of all, I would **strongly recommend not to use the user-role "user"** because according to our definition of the Keycloak user of the UI every UI-user should have that role (you can not log in into the UI if your username doesn't have the role "user"). That means if you give some permission to the role "user" every other usern will have that permission!!!

Now regarding  the issue: I don't see any bug in the UI I only see a configuration confusion namely:
The button with the Hover text `View DICOM Object` is controlled by the permission action `action-studies-download` and the Action Parameter `visible` (Viewing a an object is technically the same as downloading)

![image](https://user-images.githubusercontent.com/7990614/91740543-c0877e80-ebb3-11ea-8733-469761164a16.png)


What you configured is the permission to open a Viewer. To see the open-viewer button you have to fulfill two conditions, to have the permission (what you did) and to configure to that web-application (what you selected to get the studies) the viewer URLs (see second image)):

![image](https://user-images.githubusercontent.com/7990614/91740696-f2004a00-ebb3-11ea-8bae-07dfaaf0c7e6.png)

![image](https://user-images.githubusercontent.com/7990614/91740830-1fe58e80-ebb4-11ea-8104-5e642350b604.png)
