### ISSUE TITLE
UI Monitoring: Unify lists for Queues, Export, Retrieve, Compare, Storage Verification Tasks

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#3383]
Unify lists for Queues, Export, Retrieve, Compare, Storage Verification Tasks:

Field (property) \ Tab | Queues ✅ | Export ✅  | Retrieve ✅ | Compare ✅ | Storage Verification <br> ✅
-- | -- | -- | -- | -- | --
Device (`dicomDeviceName`)|  Y | Y | Y | Y | Y
Queue(`queue`) |  Y | Y | Y | Y | Y
Create Time (`createdTime`) | Y | Y | Y | Y | Y
Update Time (`updatedTime`) | Y | Y | Y | Y | Y
Scheduled Time (`scheduledTime`) |  Y | Y | Y | Y | Y
Process Delay (`processingStartTime` - `scheduledTime`) | Y | Y | Y | Y | Y
Process Time (`processingEndTime` - `processingStartTime`) | Y | Y | Y | Y | Y
Local AET (`LocalAET`) | Y | Y | Y | Y | Y
Remote AET (`RemoteAET`) | Y | - | Y | - | -
Exporter ID (`ExporterID`) | - | Y | - | - | -
Modality (`Modality`) | - | Y | - | - | -
#I (`NumberOfInstances`) | - | Y | - | - | -
Destination (`DestinationAET`) | - | - | Y | - | 
#I (`remaining` ->`completed`/`warning`/`failed`) | - | - | Y | - | -
Primary AET (`PrimaryAET`) | - | - | - | Y | -
Secondary AET (`SecondaryAET`) | - | - | - | Y | -
compare (`comparefield`) | - | - | - | Y | -
#S (`matches`->`missing`/`different`) | - | - | - | Y | -
Storage ID (`StorageID`) | - | - | - | - | Y
Stg.Ver.Policy (`StgCmtPolicy`) | - | - | - | - | Y
#I (`completed`/`failed`) | - | - | - | - | Y
Status (`status`) |  Y | Y | Y | Y | Y
Failures (`failures`) | Y | Y | Y | Y | Y
Batch ID (`batchID`) | Y | Y | Y | Y | Y

Always include (at least) **one** of the fields Create Time (`createdTime`), Update Time (`updatedTime`), Scheduled Time (`scheduledTime`), matching the field selected to sort by. (default: descending Update Time ). If there is enough space for a second time stamp, show Scheduled Time (`scheduledTime`) also if not sort by Scheduled Time. Requires #3388, #3389

Show `errorMessage` in hover of Failure value
Show `outcomeMessage` - or if there is no `outcomeMessage` show `errorMessage` - in hover of Status value.

**Comment by vrindanayak** [comment]
Known Limitation : If user has selected to `Order By` any of `Created Time (Desc)` / `Updated Time (Desc)` / `Scheduled Time (Desc)` switching of corresponding time columns and displaying of results works as expected if any of the `(Desc)` order by specific values is selected. 
However, on choosing any of the `(ASC)` order by values, switching of corresponding time columns works as expected, but the results are displayed still in descending order. User has to manually trigger `Submit` again to view results in `(ASC)` order for the corresponding selected time field in `Order By`
- Note this is due to UI re-using the response it already had from first triggered query. On switching of values in Order By dropdown, there is no auto invocation of service again to the server side.
