### ISSUE TITLE
UI: Move studies to another patient

### ISSUE THREAD

**Issue by bjoernalbers** [dcm4che/dcm4chee-arc-light#451]
We'd like to move studies between patients when they are linked to the wrong patient (e.g. by entering a wrong patient id at the acquisition device).
Sadly this happens a lot.
I couldn't find a way to accomplish this with the new UI.

In DCM4CHEE v2 we could simply select studies via checkboxes and move them to a new patient which works fine:

<img width="559" alt="checkboxes to select studies" src="https://cloud.githubusercontent.com/assets/117819/20304636/ac1a7374-ab31-11e6-9781-bca10aacbb3d.png">

**Comment by shral** [comment]
Hi,
you can select the study (or many studies) with CTRL + CLICK and with CTRL + X you can add those studies in the "Clipboard" (You should than see the icon on the right side) and than select the patient (Or select a study if you want to merge with an other study) and press CTRL + V.
(Instead of CTRL+ X, CTRL + C and CTRL + V you can use the right click and "copy", "paste" and "cut" too)
Best Regard
Shefki Esadi

**Comment by gunterze** [comment]
Please post questions about dcm4che at https://groups.google.com/forum/#!forum/dcm4che . Github issues are reserved for bug reports and feature requests.

**Comment by bjoernalbers** [comment]
@shral Thanks for the instructions!

@gunterze My mistake, sorry. I thought this was a bug.
