### ISSUE TITLE
STOW-RS: adjust accepted and returned content type from application/json to application/dicom+json

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#621]

**Comment by vrindanayak** [comment]
Storage works with `application/json` as well. Need below code in StowRS.java
`if (getHeaderParamValue(headerParams, "transfer-syntax") != null) {
  Map<String, String> parameters = new HashMap<>();
  parameters.put("transfer-syntax", "1.2.840.10008.1.2.4.50");
  MediaType mediaType = new MediaType("image", "jpeg", parameters);
}`
because MediaTypes.transferSyntaxOf called from StowRS.java checks for below condition : 
`String tsuid = bulkdataMediaType.getParameters().get("transfer-syntax");
   if (tsuid != null)
    return tsuid;`

**Comment by vrindanayak** [comment]
Support `not` extended on server side for `application/json`.
