### ISSUE TITLE
Disable detection of end of frame in EncapsulatedPixelDataImageInputStream for single frame images

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#752]
Detection of end of frame relies that the first two bytes of (only) the first fragment of a frame matches with the first 2 bytes of the first frame - which is not reliable, particularly, if frames are split in many small fragments. On the other hand, there is no need for such detection for single frame images, which are more likely split into multiple fragment as frames of multi-frames images. Therefore disabling detection of end of frame detection for single frame images will reduce the likelihood of failed end of frame detections significantly.

[rle.dcm.zip](https://github.com/dcm4che/dcm4chee-arc-light/files/1047747/rle.dcm.zip)
`$ dcmdump rle.dcm`
>0: [0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
132: (0002,0000) UL #4 [186] FileMetaInformationGroupLength
144: (0002,0001) OB #2 [0\1] FileMetaInformationVersion
158: (0002,0002) UI #26 [1.2.840.10008.5.1.4.1.1.7] MediaStorageSOPClassUID
192: (0002,0003) UI #54 [1.2.276.0.7230010.3.1.4.1787205428.2361.1071048149.1.
254: (0002,0010) UI #20 [1.2.840.10008.1.2.5] TransferSyntaxUID
:
1228: (7FE0,0010) OB #-1 PixelData
1240: >(FFFE,E000) #0 [] Item
1248: >(FFFE,E000) #1024 [**3\0**\0\0\64\0\0\0\-27\125\52\0\20\-90\103\0\0\0\0\0\0
2280: >(FFFE,E000) #1024 [92\86\98\83\89\93\86\83\81\78\88\84\90\101\89\84\84\
:
7080768: >(FFFE,E000) #1024 [**3\0**\0\2\1\3\0\1\2\1\4\2\0\3\2\1\2\0\1\3\1\-2\2\-1

**Comment by hczedik** [comment]
Hi @gunterze,

I have a question related to that: Why do you rely on this end of frame detection at all?
Why don't you read the offset table to find out if a frame is split into multiple fragments?

I'm asking, because in fact in some other code we do use the offset table and now we have found a dataset that does contain an incorrect offset table. Is your reason to not use the offset table, because you found it in general to be not reliable?
Can you share some history on why you decided to implement this end of frame detection?

Thanks!
Hermann

**Comment by gunterze** [comment]
For me it's questionable, if the sentence

> For a Multi-Frame Image containing only one frame or a Single Frame Image, the Basic Offset Table Item Value may be present or not. If present it will contain a single 00000000H value.

can be read as, that the Basic Offset Table is mandatory for Multi-Frame Image containing multiple frames.

**Comment by hczedik** [comment]
I would have thought that it is optional also for multiframes, but only if there is a 1:1 mapping between fragments and frames. Then it is obvious how to read them.
But if there is more than one frame and frames are split into multiple fragments, it is only logical that an offset table is mandatory. How should someone be able to read the full frames otherwise, without relying on error-prone frame end detection logic?
Have you seen multiframes out in the wild which contain frames split into multiple fragments but no offset table?

**Comment by gunterze** [comment]
I even have not yet seen single frame images with multiple data fragments, beside David's JPEG, JPEG-LS and JPEG 2000 compressed transfer syntax test DICOM images at ftp://medical.nema.org/MEDICAL/Dicom/DataSets/WG04 .

Posted the question at https://groups.google.com/forum/#!topic/comp.protocols.dicom/mQxT7lAgSuw .

**Comment by hczedik** [comment]
Thanks for posting the question. I still think the end-of-frame detection you use is too risky.
It would be better to rely on the offset table, if it is available.
If it is not available, and you don't want to implement the rather complex logic that David Clunie is describing, then it would be better to simply assume the fragments are perfectly aligned with the frames (if NumberOfFrames > 1).
I checked in our (client) code: If there is no offset table and it is a multiframe (NumberOfFrames > 1), we simply assume that one fragment is one frame. We have this code since many years, and never had problems.
Therefore I think data where this doesn't assumption is not true, simply doesn't exist. @wayfarer3130 (Bill) also confirmed that.

**Comment by gunterze** [comment]
But there is also no evidence, that the used algorithm fails on existing JPEG data. The issue pops up for RLE, where DICOM explicitly does not allow to split encoded frames over multiple data fragments. => dcm4che/dcm4che#412 .
